name: Tests

on: [push]

jobs:
  test:
    name: MySQL ${{ matrix.mysql }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        mysql: [8.0, 5.7]

    services:
      mysql:
        image: mysql:${{ matrix.mysql }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel_eloquent_spatial_test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify MySQL connection
        run: |
          mysql --version
          sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -u root -e 'CREATE DATABASE IF NOT EXISTS laravel_eloquent_spatial_test;'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Execute tests
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
        run: vendor/bin/phpunit
