name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        laravel: [8.*]
        mysql: [8.0, 5.7]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: 8.*
            testbench: 6.*

    name: Laravel ${{ matrix.laravel }} - MySQL ${{ matrix.mysql }} - ${{ matrix.stability }}

    services:
      mysql:
        image: mysql:${{ matrix.mysql }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel_eloquent_spatial_test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

#      - name: Shutdown Ubuntu MySQL
#        if: ${{ matrix.os == 'ubuntu-latest'}}
#        run: sudo service mysql stop
#
#      - name: Setup MySQL
#        uses: mirromutth/mysql-action@v1.1
#        with:
#          mysql version: ${{ matrix.mysql }}
#          mysql database: 'laravel_eloquent_spatial_test'
#          mysql user: 'root'
#          mysql password: "root"

      - name: Execute tests
        run: vendor/bin/phpunit
